version: "3.7"

services:
  server:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run develop"
    ports:
      - 1337:1337
    working_dir: /server
    volumes:
      - ./:/server
    depends_on:
      - db

  db:
    image: postgres:13.2
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
